#!/usr/bin/env bash
#script that will display information about subdomains
info_func() {
    ldig=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:'| tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $ldig" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  info_func "$1" "www"
  info_func "$1" "lb-01"
  info_func "$1" "web-01"
  info_func "$1" "web-02"
elif [ "$#" == 2 ]
then
  info_func "$1" "$2"
fi
