#!/usr/bin/env bash
#script that install nginx on my web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/indedx.nginx-debian.html
sudo service nginx restart
