#!/usr/bin/env bash
#script that install nginx on my web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo /etc/init.d/ngingx restart
