#!/usr/bin/env bash
#Install and configure HAproxy
sudo apt-get update
sudo apt-get install -y haproxy=1.6.\*
cat >>  /etc/haproxy/haproxy.cfg << EOL

frontend front
    bind *:80
    default_backend back
backend back
    balance roundrobin
    server 1492-web-01 34.75.200.174:80 check
    server 1492-web-02 34.229.85.234:80 check
EOL
sudo /etc/init.d/haproxy restart