#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.
sudo mysqldump -u root -p"$1" --all-databases > backup.sql
sudo tar cfz "$(date +%d-%m-%Y).tar.gz" backup.sql
