#!/usr/bin/env bash
#listening on port 80
service nginx stop                                                                                                         
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default                                                                      
sed -i 's/8080/80/g' /etc/nginx/sites-available/default                                                                    
service nginx start  