#!/usr/bin/env bash
#scrpit to create a file , run a loop and kill it
echo "$$" > /var/run/holbertonscript.pid
x=1
while [ $x ]
do
	echo "To infinity and beyond"
	trap "echo Y U no love me?!" SIGINT
	trap "echo I hate the kill command; -rm /var/run/holbertonscript.pid; exit" SIGTERM
	trap "rm /var/run/holbertonscript.pid" SIGQUIT
	sleep 2
done
