#!/usr/bin/env bash
#internal variables
while IFS=: read v1 v2 v3 v4 v5 v6 v7
do
	printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$v1" "$v4" "$v6" "$v7" "$v3" "$v2" "$v5"
done < "/etc/passwd"
