#!/usr/bin/env bash
#script that make Nginx running as the nginx user.
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
