#!/usr/bin/env bash
#script that make Nginx running as the nginx user
pkill apache2
chmod 777 /etc/nginx/nginx.conf
chown nginx /etc/nginx -R
sed -i 's/80/8080/g' /etc/nginx/sites-available/default 
sudo -u nginx service nginx restart
